# Generated by Django 5.2.3 on 2025-06-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
